#' Currency codes and currency representation attributes
#' @description Create a data frame containing attributes
#' of ISO 4217 currency codes and the accepted means to
#' represent the monetary values
#' @export currency

currency <- function(){

  iso_4217_code <- c(
    "AED", "AFN", "ALL", "AMD", "ANG", "AOA",
    "ARS", "AUD", "AWG", "AZN", "BAM", "BBD",
    "BDT", "BGN", "BHD", "BIF", "BMD", "BND",
    "BOB", "BOV", "BRL", "BSD", "BTN", "BWP",
    "BYR", "BZD", "CAD", "CDF", "CHE", "CHF",
    "CHW", "CLF", "CLP", "CNY", "COP", "COU",
    "CRC", "CUC", "CUP", "CVE", "CZK", "DJF",
    "DKK", "DOP", "DZD", "EGP", "ERN", "ETB",
    "EUR", "FJD", "FKP", "GBP", "GEL", "GHS",
    "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD",
    "HNL", "HRK", "HTG", "HUF", "IDR", "ILS",
    "INR", "IQD", "IRR", "ISK", "JMD", "JOD",
    "JPY", "KES", "KGS", "KHR", "KMF", "KPW",
    "KRW", "KWD", "KYD", "KZT", "LAK", "LBP",
    "LKR", "LRD", "LSL", "LYD", "MAD", "MDL",
    "MGA", "MKD", "MMK", "MNT", "MOP", "MRO",
    "MUR", "MVR", "MWK", "MXN", "MXV", "MYR",
    "MZN", "NAD", "NGN", "NIO", "NOK", "NPR",
    "NZD", "OMR", "PAB", "PEN", "PGK", "PHP",
    "PKR", "PLN", "PYG", "QAR", "RON", "RSD",
    "RUB", "RWF", "SAR", "SBD", "SCR", "SDG",
    "SEK", "SGD", "SHP", "SLL", "SOS", "SRD",
    "SSP", "STD", "SYP", "SZL", "THB", "TJS",
    "TMT", "TND", "TOP", "TRY", "TTD", "TWD",
    "TZS", "UAH", "UGX", "USD", "USN", "USS",
    "UYI", "UYU", "UZS", "VEF", "VND", "VUV",
    "WST", "XAF", "XAG", "XAU", "XCD", "XDR",
    "XOF", "XPD", "XPF", "XPT", "XSU", "XUA",
    "YER", "ZAR", "ZMW"
  )

  curr_number <- c(
    "784", "971", "8", "51", "532", "973",
    "32", "36", "533", "944", "977", "52",
    "50", "975", "48", "108", "60", "96",
    "68", "984", "986", "44", "64", "72",
    "974", "84", "124", "976", "947", "756",
    "948", "990", "152", "156", "170", "970",
    "188", "931", "192", "132", "203", "262",
    "208", "214", "12", "818", "232", "230",
    "978", "242", "238", "826", "981", "936",
    "292", "270", "324", "320", "328", "344",
    "340", "191", "332", "348", "360", "376",
    "356", "368", "364", "352", "388", "400",
    "392", "404", "417", "116", "174", "408",
    "410", "414", "136", "398", "418", "422",
    "144", "430", "426", "434", "504", "498",
    "969", "807", "104", "496", "446", "478",
    "480", "462", "454", "484", "979", "458",
    "943", "516", "566", "558", "578", "524",
    "554", "512", "590", "604", "598", "608",
    "586", "985", "600", "634", "946", "941",
    "643", "646", "682", "90", "690", "938",
    "752", "702", "654", "694", "706", "968",
    "728", "678", "760", "748", "764", "972",
    "934", "788", "776", "949", "780", "901",
    "834", "980", "800", "840", "997", "998",
    "940", "858", "860", "937", "704", "548",
    "882", "950", "961", "959", "951", "960",
    "952", "964", "953", "962", "994", "965",
    "886", "710", "967")

  exponent <- c(
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 3, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
    2, 2, 2, 2, 2, 4, 0, 2, 2, 2, 2, 2, 2,
    0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 3, 2, 0, 2, 3, 0, 2, 2, 2, 0, 2,
    0, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 1,
    2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 0,
    2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2,
    2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0,
    2, 0, NA, NA, 2, NA, 0, NA, 0, NA, NA,
    NA, 2, 2, 2)

  currency_name <- c(
    "United Arab Emirates dirham", "Afghan afghani",
    "Albanian lek", "Armenian dram",
    "Netherlands Antillean guilder", "Angolan kwanza",
    "Argentine peso", "Australian dollar",
    "Aruban florin", "Azerbaijani manat",
    "Bosnia and Herzegovina convertible mark",
    "Barbados dollar", "Bangladeshi taka",
    "Bulgarian lev", "Bahraini dinar", "Burundian franc",
    "Bermudian dollar", "Brunei dollar",
    "Boliviano", "Bolivian Mvdol", "Brazilian real",
    "Bahamian dollar", "Bhutanese ngultrum", "Botswana pula",
    "Belarusian ruble", "Belize dollar", "Canadian dollar",
    "Congolese franc", "WIR Bank", "Swiss franc",
    "WIR Bank", "Unidad de Fomento", "Chilean peso",
    "Renminbi", "Colombian peso", "Unidad de Valor Real",
    "Costa Rican colon", "Cuban convertible peso",
    "Cuban peso", "Cape Verde escudo", "Czech koruna",
    "Djiboutian franc", "Danish krone", "Dominican peso",
    "Algerian dinar", "Egyptian pound", "Eritrean nakfa",
    "Ethiopian birr", "Euro", "Fiji dollar",
    "Falkland Islands pound", "Pound sterling",
    "Georgian lari", "Ghanaian cedi", "Gibraltar pound",
    "Gambian dalasi", "Guinean franc", "Guatemalan quetzal",
    "Guyana dollar", "Hong Kong dollar", "Honduran lempira",
    "Croatian kuna", "Haitian gourde", "Hungarian forint",
    "Indonesian rupiah", "Israeli new shekel", "Indian rupee",
    "Iraqi dinar", "Iranian rial", "Icelandic kr\u00f3na",
    "Jamaican dollar", "Jordanian dinar", "Japanese yen",
    "Kenyan shilling", "Kyrgyzstani som", "Cambodian riel",
    "Comoro franc", "North Korean won", "South Korean won",
    "Kuwaiti dinar", "Cayman Islands dollar",
    "Kazakhstani tenge", "Lao kip", "Lebanese pound",
    "Sri Lankan rupee", "Liberian dollar", "Lesotho loti",
    "Libyan dinar", "Moroccan dirham", "Moldovan leu",
    "Malagasy ariary", "Macedonian denar", "Myanmar kyat",
    "Mongolian t\u00f6gr\u00f6g", "Macanese pataca",
    "Mauritanian ouguiya", "Mauritian rupee",
    "Maldivian rufiyaa", "Malawian kwacha", "Mexican peso",
    "Mexican Unidad de Inversion", "Malaysian ringgit",
    "Mozambican metical", "Namibian dollar",
    "Nigerian naira", "Nicaraguan c\u00f3rdoba",
    "Norwegian krone", "Nepalese rupee",
    "New Zealand dollar", "Omani rial", "Panamanian balboa",
    "Peruvian Sol", "Papua New Guinean kina",
    "Philippine peso", "Pakistani rupee", "Polish z\u0142oty",
    "Paraguayan guaran\u00ed", "Qatari riyal", "Romanian Leu",
    "Serbian dinar", "Russian ruble", "Rwandan franc",
    "Saudi riyal", "Solomon Islands dollar",
    "Seychelles rupee", "Sudanese pound", "Swedish krona",
    "Singapore dollar", "Saint Helena pound",
    "Sierra Leonean leone", "Somali shilling",
    "Surinamese dollar", "South Sudanese pound",
    "S\u00e3o Tom\u00e9 and Pr\u00edncipe dobra", "Syrian pound",
    "Swazi lilangeni", "Thai baht", "Tajikistani somoni",
    "Turkmenistani manat", "Tunisian dinar",
    "Tongan pa\u02bbanga", "Turkish lira",
    "Trinidad and Tobago dollar", "New Taiwan dollar",
    "Tanzanian shilling", "Ukrainian hryvnia",
    "Ugandan shilling", "United States dollar",
    "United States dollar", "United States dollar",
    "Uruguay Peso en Unidades Indexadas", "Uruguayan peso",
    "Uzbekistan som", "Venezuelan bol\u00edvar",
    "Vietnamese dong", "Vanuatu vatu",
    "Samoan tala", "Central African CFA franc", "Silver",
    "Gold", "East Caribbean dollar", "Special drawing rights",
    "West African CFA franc", "Palladium", "CFP franc",
    "Platinum", "XSU", "XUA", "Yemeni rial",
    "South African rand", "Zambian kwacha")

  symbol <- c(
    "AED", "\u060b", "Lek", "\u058f",
    "f", "Kz", "$", "$",
    "f", "\u20bc", "KM", "$",
    "\u09f3", "\u043b\u0432", "BD", "FBu",
    "$", "$", "$b", "BOV",
    "R$", "$", "Nu.", "P",
    "p.", "BZ$", "$", "FC",
    "CHE", "CHF", "CHW", "UF",
    "$", "\u00a5", "$", "COU",
    "\u20a1", "CUC$", "$", "$",
    "K\u010d", "Fdj", "kr", "RD$",
    "DA", "\u00a3", "Nfk", "Br",
    "\u20a0", "$", "\u00a3", "\u00a3",
    "\u20be", "\u20b5", "\u00a3", "D",
    "FG", "Q", "$", "$",
    "L", "kn", "G", "Ft",
    "Rp", "\u20aa", "\u20b9", "IQD",
    "\ufdfc", "kr", "J$", "JD",
    "\u00a5", "KSh", "KGS", "\u17db",
    "CF", "\uffe6", "\uffe6", "K.D",
    "$", "\u20b8", "\u20ad", "\u00a3",
    "Rs", "$", "L", "LD",
    "MAD", "MDL", "MGA", "\u0434\u0435\u043d",
    "K", "\u20ae", "MOP$", "UM",
    "Rs", "MRf", "MK", "$",
    "MXV", "RM ", "MT", "$",
    "\u20a6", "C$", "kr", "Rs",
    "$", "\ufdfc", "B/.", "S/.",
    "K", "\u20b1", "Rs", "z\u0142",
    "\u20b2", "QR", "lei", "\u0414\u0438\u043d.",
    "\u20bd", "FRw", "\ufdfc", "$",
    "Rs", "\u00a3", "kr", "$",
    "\u00a3", "Le", "S", "$",
    "\u00a3", "Db", "\u00a3", "L",
    "\u0e3f", "TJS", "\u20bc", "DT",
    "T$", "\u20ba", "TT$", "NT$",
    "TSh", "\u20b4", "USh", "$",
    "$", "$", "UYI", "$U",
    "\u043b\u0432", "Bs", "\u20ab", "VT",
    "WS$", "FCFA", "XAG", "XAU",
    "$", "XDR", "CFA", "XPD",
    "F", "XPT", "XSU", "XUA",
    "\ufdfc", "R", "ZMW")

  currency_values <-
    data.frame(iso_4217_code, curr_number,
               exponent, currency_name, symbol,
               stringsAsFactors = FALSE)

  return(currency_values)
}
